Add the Compress function (#4)
h-dav/itertools pull request #10
Opened 2022-04-15 13:50 UTC by khnom5000

Add the Compress function (#4)

2022-04-15 14:36 UTC, khnom5000 commented
running over the selector will result in a "panic: runtime error: index out of range", not sure how this wants wants to be handled if at all, left it as default for now

2022-04-17 11:40 UTC, khnom5000 commented
added a selector len check to stop panic in prev comment, i will also add a benchmark test in

2022-04-17 15:00 UTC, h-dav requested changes
Happy with functionality, just a comment about a comment, and a suggestion

2022-04-19 09:01 UTC, khnom5000 commented on itertools.go
> +func Compress[T any](data []T, selector []bool) (ch Iterator) {
will do :)

2022-04-19 09:07 UTC, khnom5000 commented on itertools.go
> +			if len(selector) > i && selector[i] {
by doing this it think we then limit ourselves, for example:
if i have data = [1,2,3,4,5,6,7,8,9,0]
and selector = [T,T,F,T]
if i just want values [1,2,4] in the return, then i would need to pad False on the end of the array 6 times or be hit with a check, currently this function would just accept the data and selector above and return [1,2,4].
what do you think?

2022-04-19 17:15 UTC, h-dav approved these changes

2022-04-19 17:15 UTC, h-dav commented on itertools.go
> +			if len(selector) > i && selector[i] {
Ah yeah that's a good point. Happy with this now

2022-04-19 17:16 UTC, merged